from reportlab.lib.pagesizes import A4

PAGASIZE = A4
DOC_WIDTH, DOC_HEIGHT = PAGASIZE
DOC_LEFT_MARGIN = 100
DOC_RIGHT_MARGIN = 100
DOC_TOP_MARGIN = 100 
DOC_BOTTOM_MARGIN = 100 
DOC_WIDTH_REAL = DOC_WIDTH - (DOC_LEFT_MARGIN + DOC_RIGHT_MARGIN)
DOC_HEIGHT_REAL = DOC_HEIGHT - (DOC_TOP_MARGIN + DOC_BOTTOM_MARGIN)
