from reportlab.lib.pagesizes import A4


class Setting:

    PAGASIZE = A4
    DOC_WIDTH, DOC_HEIGHT = PAGASIZE
    DOC_LEFT_MARGIN = 100
    DOC_RIGHT_MARGIN = 100
    DOC_TOP_MARGIN = 100 
    DOC_BOTTOM_MARGIN = 100 
    DOC_WIDTH_REAL = DOC_WIDTH - (DOC_LEFT_MARGIN + DOC_RIGHT_MARGIN)
    DOC_HEIGHT_REAL = DOC_HEIGHT - (DOC_TOP_MARGIN + DOC_BOTTOM_MARGIN)

    @classmethod
    def update(cls):
        cls.DOC_WIDTH_REAL = cls.DOC_WIDTH - (cls.DOC_LEFT_MARGIN + cls.DOC_RIGHT_MARGIN)
        cls.DOC_HEIGHT_REAL = cls.DOC_HEIGHT - (cls.DOC_TOP_MARGIN + cls.DOC_BOTTOM_MARGIN)
